CREATE TABLE IF NOT EXISTS public.products (id bigserial NOT NULL,
                                                         product_name character varying(50) NOT NULL,
                                                                                            product_category int NOT NULL,
                                                                                                                 product_color int NOT NULL,
                                                                                                                                   product_photo int NOT NULL,
                                                                                                                                                     product_materials int NOT NULL,
                                                                                                                                                                           price int NOT NULL,
                                                                                                                                                                                     sub_category int NOT NULL,
                                                                                                                                                                                                      product_description text NOT NULL,
                                                                                                                                                                                                                               product_state int NOT NULL,
                                                                                                                                                                                                                                                 product_owner int NOT NULL,
                                                                                                                                                                                                                                                                   PRIMARY KEY (id),
                                            FOREIGN KEY (product_color) REFERENCES public.product_color (id),
                                            FOREIGN KEY (product_category) REFERENCES public.product_categories (id),
                                            FOREIGN KEY (product_photo) REFERENCES public.product_photos (id),
                                            FOREIGN KEY (product_materials) REFERENCES public.product_materials (id),
                                            FOREIGN KEY (sub_category) REFERENCES public.sub_categories (id),
                                            FOREIGN KEY (product_state) REFERENCES public.product_state (id),
                                            FOREIGN KEY (product_owner) REFERENCES public.user_accounts (id));